# Generated by Django 5.0.7 on 2024-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_productcategory_alter_product_slug_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(max_length=200, verbose_name='url'),
        ),
    ]
